/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.boxes.formas;

import java.util.LinkedList;
import javax.swing.JCheckBox;
import uam.pvoe.boxes.operaciones.OperacionesCheckBox;

/**
 *
 * @author pedro
 */
public class CBox extends javax.swing.JFrame {

    LinkedList <JCheckBox> listaCBLenguajes = new LinkedList(); //debe ser global
    /**
     * Creates new form CBox
     */
    public CBox() {
        initComponents();
        agruparCheckBoxesLenguajes();
        txtOtroLenguaje.setVisible(false);
    }
    
    public void agruparCheckBoxesLenguajes(){
        //esto es para agruparlos
        listaCBLenguajes.add(cbC);
        listaCBLenguajes.add(cbCPP);
        listaCBLenguajes.add(cbJava);
        listaCBLenguajes.add(cbOtro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbllenguajes = new javax.swing.JLabel();
        cbC = new javax.swing.JCheckBox();
        cbCPP = new javax.swing.JCheckBox();
        cbJava = new javax.swing.JCheckBox();
        cbOtro = new javax.swing.JCheckBox();
        lblIdiomas = new javax.swing.JLabel();
        cbIngles = new javax.swing.JCheckBox();
        cbFrances = new javax.swing.JCheckBox();
        cbAleman = new javax.swing.JCheckBox();
        lblPreferencias = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        txtOtroLenguaje = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbllenguajes.setText("Lenguajes");

        cbC.setText("C");

        cbCPP.setText("C++");

        cbJava.setText("Java");

        cbOtro.setText("Otro");
        cbOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOtroActionPerformed(evt);
            }
        });

        lblIdiomas.setText("Idiomas");

        cbIngles.setText("Inglés");

        cbFrances.setText("Francés");

        cbAleman.setText("Alemán");

        lblPreferencias.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblPreferencias.setText("Preferencias de Cursos");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPreferencias)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbllenguajes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblIdiomas)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbCPP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbFrances)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbJava)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbAleman)
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbOtro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbC, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbIngles)
                        .addGap(89, 89, 89))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(txtOtroLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(btnRegistrar)
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblPreferencias)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllenguajes)
                    .addComponent(lblIdiomas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbC)
                    .addComponent(cbIngles))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCPP)
                    .addComponent(cbFrances))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbJava)
                    .addComponent(cbAleman))
                .addGap(18, 18, 18)
                .addComponent(cbOtro)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOtroLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
      //para imprimir en pantalla los datos que se ingresan en la ventana
      OperacionesCheckBox operaciones = new OperacionesCheckBox();
      LinkedList <String> lenguajes;
      lenguajes = operaciones.obtenerCursosLenguajes(listaCBLenguajes);
      System.out.println(txtOtroLenguaje.getText());
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cbOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOtroActionPerformed
        //esto es para que aparezca y desaparezca la cajita de texto
        txtOtroLenguaje.setText("");
        if(cbOtro.isSelected()){
            txtOtroLenguaje.setVisible(true);
            setVisible(true);
        }
        else{
            txtOtroLenguaje.setVisible(false);
        }
    }//GEN-LAST:event_cbOtroActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox cbAleman;
    private javax.swing.JCheckBox cbC;
    private javax.swing.JCheckBox cbCPP;
    private javax.swing.JCheckBox cbFrances;
    private javax.swing.JCheckBox cbIngles;
    private javax.swing.JCheckBox cbJava;
    private javax.swing.JCheckBox cbOtro;
    private javax.swing.JLabel lblIdiomas;
    private javax.swing.JLabel lblPreferencias;
    private javax.swing.JLabel lbllenguajes;
    private javax.swing.JTextField txtOtroLenguaje;
    // End of variables declaration//GEN-END:variables
}
